readded faliure checl

diff --git a/.github/workflows/localPa11y.yml b/.github/workflows/localPa11y.yml
--- a/.github/workflows/localPa11y.yml
+++ b/.github/workflows/localPa11y.yml
@@ -37,3 +37,12 @@ jobs:
         path: ./pa11y_output.txt
 
 
+```${{ steps.pa11y_output.outputs.content }}```
+
+</details>'
+
+    - name: Check for pa11y failures.
+      if: contains(steps.pa11y_output.outputs.content, 'errno 2')
+      run: |
+        echo "::error::The site is failing accessibility tests. Please review the comment in the pull request or the pa11y-ci step in the workflow for details."
+        exit 1
