added error handling to pa11y github action

diff --git a/.github/workflows/localPa11y.yml b/.github/workflows/localPa11y.yml
--- a/.github/workflows/localPa11y.yml
+++ b/.github/workflows/localPa11y.yml
@@ -28,4 +28,21 @@ jobs:
     - run: npm install -g pa11y-ci
     - run: npm install wait-on
     - run: npm start & npx wait-on http://localhost:3000
-    - run: pa11y-ci --config ./localPa11y.json
+    - run: pa11y-ci --config ./localPa11y.json | tee pa11y_output.txt
+        
+    - name: Read pa11y_output file.
+      id: pa11y_output
+      uses: juliangruber/read-file-action@v1
+      with:
+        path: ./pa11y_output.txt
+
+
+```${{ steps.pa11y_output.outputs.content }}```
+
+</details>'
+
+    - name: Check for pa11y failures.
+      if: contains(steps.pa11y_output.outputs.content, 'errno 2')
+      run: |
+        echo "::error::The site is failing accessibility tests. Please review the comment in the pull request or the pa11y-ci step in the workflow for details."
+        exit 1
